workflows:
  ios-workflow:
    name: Build iOS App
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        APP_ID: "com.macfara.rifa_app_new"
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Build iOS
        script: |
          flutter build ios --release --no-codesign
      - name: Package .app to .ipa
        script: |
          mkdir -p build/ios/ipa
          cd build/ios/iphoneos
          for app in *.app; do
            filename="${app%.app}"
            cd ..
            xcrun -sdk iphoneos PackageApplication -v "iphoneos/$app" -o "$(pwd)/ipa/$filename.ipa"
            cd iphoneos
          done
    artifacts:
      - build/ios/iphoneos/*.app
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - pglezlo@icloud.com